Cart page
abhishektanwar/VYBE-ECOMMERCE pull request #4
Opened 2022-03-21 04:17 UTC by abhishektanwar

Files to check:

- src/screens/Cart/index.jsx
- src/screens/Cart/cart.css
- src/components/TicketContainer/index.jsx
- src/components/ProductCard/index.jsx (line 16 - 98, horizontal variant)

2022-03-21 06:04 UTC, zoyatanweer commented on src/screens/Cart/cart.css
> +	color: var(--black-color);
you can write background color and color together, this way the user shouldn't have to go through all the lines in between.

2022-03-21 06:04 UTC, zoyatanweer commented on src/screens/Cart/cart.css
> +} */
remove commented code if not required

2022-03-21 06:07 UTC, zoyatanweer commented on src/components/ProductCard/product-card.css
> +  min-width: 280px;
these two can be in rem

2022-03-21 06:07 UTC, zoyatanweer commented on src/components/ProductCard/product-card.css
> +  /* background: chartreuse; */
remove commented code if not required.

2022-03-21 06:10 UTC, zoyatanweer commented on src/components/ProductCard/product-card.css
> +}
I like the way how you used the 'direct child selector' here. Nice.

2022-03-21 06:11 UTC, zoyatanweer commented on src/components/ProductCard/product-card.css
> +  color:var(--primary-color)
semicolon not needed here?

2022-03-21 06:11 UTC, zoyatanweer commented on src/components/ProductCard/product-card.css
> +  margin: auto 0.6rem;
isn't it small value? it can be in px here I think.

2022-03-21 06:13 UTC, zoyatanweer approved these changes
code is clean and easily understandable. Good to merge with suggested changes. Great work Abhishek.

2022-03-21 08:32 UTC, sudipkundu999 requested changes
The UI looks good and so is the code.

The naming of files is inconsistent.
In the ProductListing component, you've named the file as `ProductListing.jsx` while in other places you've named it as `index.jsx`. It would become difficult to work with multiple files with the same names doing different things.

As a rule of thumb:
When you're making a component eg. TicketContainer name the file as `TicketContainer.jsx` and not `index.jsx`

Also, use the `index.js` file for import-export, this will avoid multiple import lines
eg. in App.js (line 5,7,8) for 3 screens there are 3 import lines.
As the number of screens increases import lines will also increase.

If you keep an index.js in screens folder then this will reduce to 
`import {ProductListing, Wishlist, Cart} from "./screens"`

2022-03-22 06:55 UTC, abhishektanwar commented
> Yes I understood what you are trying to convey here but to me, it makes more sense to have `index.js` file as it helps me in understanding what is the starter file and where to begin from in a folder. 

> Coming to keeping an `index.js` file in 'screens` directory, that can still be done. I'll make this older structure change once all the current branches are merged

2022-03-22 07:04 UTC, abhishektanwar commented on src/screens/Cart/cart.css
> +} */
removed

2022-03-22 07:05 UTC, abhishektanwar commented on src/components/ProductCard/product-card.css
> +  min-width: 280px;
fixed.

2022-03-22 07:05 UTC, abhishektanwar commented on src/components/ProductCard/product-card.css
> +  /* background: chartreuse; */
removed

2022-03-22 07:39 UTC, sudipkundu999 approved these changes
The reasoning for keeping `index.js` as file name makes sense now.
Good work. Good to merge.

2022-03-22 09:24 UTC, merged